baseURL = "https://junya-masuda.github.io/"
languageCode = "ja"
title = "junya-masuda"
theme = "PaperMod"
buildFuture = true

[params]
  math = true

[markup.goldmark.extensions.passthrough]
  enable = true

[markup.goldmark.extensions.passthrough.delimiters]
  block = [["\$\$", "\$\$"]]
  inline = [["\$", "\$"]]
