baseURL = "https://junya-masuda.github.io/"
languageCode = "ja"
title = "junya-masuda"
theme = "PaperMod"
buildFuture = true

[params]
  math = true
  homeInfoParams = {Title = "junya-masuda", Content = "学んだことをアウトプットするサイト"}

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/junya-masuda"

[markup.goldmark.extensions.passthrough]
  enable = true

[markup.goldmark.extensions.passthrough.delimiters]
  block = [["76316", "76316"]]
  inline = [["$", "$"]]
